param()

# Verifica se está sendo executado como administrador
if (-not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
    Write-Error "Este script precisa ser executado como administrador."
    Exit 1
}

try {
    $AppName = "NOME DO APP"
    $CompanyName = "NOME DA EQUIPE"
    $InstallBasePath = "$env:ProgramFiles\$CompanyName"
    $InstallDir = Join-Path $InstallBasePath $AppName

    $ProgramsPath = "$env:ProgramData\Microsoft\Windows\Start Menu\Programs"
    $ShortcutName = "PowerSign.lnk"
    $ShortcutFilePath = Join-Path $ProgramsPath $ShortcutName

    $RegistryPath = "HKLM:\Software\$CompanyName\$AppName"

    Write-Host "Iniciando desinstalação do $AppName..."

    # 1. Remove a chave de registro
    if (Test-Path $RegistryPath) {
        Remove-Item -Path $RegistryPath -Recurse -Force -ErrorAction SilentlyContinue
        Write-Host "Chave de registro removida: $RegistryPath"
    } else {
        Write-Host "Chave de registro não encontrada: $RegistryPath"
    }

    # 2. Remove o atalho
    if (Test-Path $ShortcutFilePath) {
        Remove-Item -Path $ShortcutFilePath -Force -ErrorAction SilentlyContinue
        Write-Host "Atalho removido: $ShortcutFilePath"
    } else {
        Write-Host "Atalho não encontrado: $ShortcutFilePath"
    }

    # 3. Remove o diretório de instalação
    if (Test-Path $InstallDir) {
        Remove-Item -Path $InstallDir -Recurse -Force -ErrorAction SilentlyContinue
        Write-Host "Diretório de instalação removido: $InstallDir"
    } else {
        Write-Host "Diretório de instalação não encontrado: $InstallDir"
    }

    # 4. Remove o diretório base se estiver vazio
    if (Test-Path $InstallBasePath) {
        if ((Get-ChildItem -Path $InstallBasePath -Force -ErrorAction SilentlyContinue).Count -eq 0) {
            Remove-Item -Path $InstallBasePath -Recurse -Force -ErrorAction SilentlyContinue
            Write-Host "Diretório base removido: $InstallBasePath"
        } else {
            Write-Host "Diretório base não está vazio: $InstallBasePath"
        }
    }

    Write-Host "$AppName desinstalado com sucesso!"
    Exit 0
} catch {
    Write-Error "ERRO DURANTE A DESINSTALAÇÃO: $($_.Exception.Message)"
    Exit 1
}
# SIG # Begin signature block
# MIIlAgYJKoZIhvcNAQcCoIIk8zCCJO8CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDhVGxFYzgyI5DV
# PxL7G/SEfaNrhghws841/YRfqzXLlKCCHyUwggWNMIIEdaADAgECAhAOmxiO+dAt
# 5+/bUOIIQBhaMA0GCSqGSIb3DQEBDAUAMGUxCzAJBgNVBAYTAlVTMRUwEwYDVQQK
# EwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xJDAiBgNV
# BAMTG0RpZ2lDZXJ0IEFzc3VyZWQgSUQgUm9vdCBDQTAeFw0yMjA4MDEwMDAwMDBa
# Fw0zMTExMDkyMzU5NTlaMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2Vy
# dCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lD
# ZXJ0IFRydXN0ZWQgUm9vdCBHNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
# ggIBAL/mkHNo3rvkXUo8MCIwaTPswqclLskhPfKK2FnC4SmnPVirdprNrnsbhA3E
# MB/zG6Q4FutWxpdtHauyefLKEdLkX9YFPFIPUh/GnhWlfr6fqVcWWVVyr2iTcMKy
# unWZanMylNEQRBAu34LzB4TmdDttceItDBvuINXJIB1jKS3O7F5OyJP4IWGbNOsF
# xl7sWxq868nPzaw0QF+xembud8hIqGZXV59UWI4MK7dPpzDZVu7Ke13jrclPXuU1
# 5zHL2pNe3I6PgNq2kZhAkHnDeMe2scS1ahg4AxCN2NQ3pC4FfYj1gj4QkXCrVYJB
# MtfbBHMqbpEBfCFM1LyuGwN1XXhm2ToxRJozQL8I11pJpMLmqaBn3aQnvKFPObUR
# WBf3JFxGj2T3wWmIdph2PVldQnaHiZdpekjw4KISG2aadMreSx7nDmOu5tTvkpI6
# nj3cAORFJYm2mkQZK37AlLTSYW3rM9nF30sEAMx9HJXDj/chsrIRt7t/8tWMcCxB
# YKqxYxhElRp2Yn72gLD76GSmM9GJB+G9t+ZDpBi4pncB4Q+UDCEdslQpJYls5Q5S
# UUd0viastkF13nqsX40/ybzTQRESW+UQUOsxxcpyFiIJ33xMdT9j7CFfxCBRa2+x
# q4aLT8LWRV+dIPyhHsXAj6KxfgommfXkaS+YHS312amyHeUbAgMBAAGjggE6MIIB
# NjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTs1+OC0nFdZEzfLmc/57qYrhwP
# TzAfBgNVHSMEGDAWgBRF66Kv9JLLgjEtUYunpyGd823IDzAOBgNVHQ8BAf8EBAMC
# AYYweQYIKwYBBQUHAQEEbTBrMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdp
# Y2VydC5jb20wQwYIKwYBBQUHMAKGN2h0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNv
# bS9EaWdpQ2VydEFzc3VyZWRJRFJvb3RDQS5jcnQwRQYDVR0fBD4wPDA6oDigNoY0
# aHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJlZElEUm9vdENB
# LmNybDARBgNVHSAECjAIMAYGBFUdIAAwDQYJKoZIhvcNAQEMBQADggEBAHCgv0Nc
# Vec4X6CjdBs9thbX979XB72arKGHLOyFXqkauyL4hxppVCLtpIh3bb0aFPQTSnov
# Lbc47/T/gLn4offyct4kvFIDyE7QKt76LVbP+fT3rDB6mouyXtTP0UNEm0Mh65Zy
# oUi0mcudT6cGAxN3J0TU53/oWajwvy8LpunyNDzs9wPHh6jSTEAZNUZqaVSwuKFW
# juyk1T3osdz9HNj0d1pcVIxv76FQPfx2CWiEn2/K2yCNNWAcAgPLILCsWKAOQGPF
# mCLBsln1VWvPJ6tsds5vIy30fnFqI2si/xK4VC0nftg62fC2h5b9W9FcrBjDTZ9z
# twGpn1eqXijiuZQwggXbMIIEw6ADAgECAhNKAAURxoKih7180ND7AAAABRHGMA0G
# CSqGSIb3DQEBCwUAMEYxEzARBgoJkiaJk/IsZAEZFgNuZXQxGTAXBgoJkiaJk/Is
# ZAEZFglib3RpY2FyaW8xFDASBgNVBAMTC3N1YjMtQ0FCb3RpMB4XDTI1MDIwNjE3
# MDc0MFoXDTI2MDIwNjE3MDc0MFowIzEhMB8GA1UEAwwYQUVfTWFyY29zIFBhdWxv
# IFN0b2tvX0FFMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvsxLCDoV
# tsEb7uigr5JMGh2+e9Hd/DwFIOXfJnsZX/CrSiCnMU1n5Yt3CXc8dzy8NijmGHtI
# l6TMEn/gTb4OcF8eHki1/OIz/EU1XBUei3hIJZI2Y6qFre9YonuP/GUi3hcUPAlB
# jaWfVaWf8PfkIRDDTlxJlfBwLXgZgu8PjVGPXEXQPGSA9IUF1ECWeACtbth8yULa
# dXeSPZ3aChWq+QPVz+ISKv+7EscG2XcZpST3VRJHya1eOAzuV24a6fEVjJlpGeIp
# Wl2+wGLhayZPI2l9hqalt4lywKVIAR6YVxx6+6eO+MQvjd7ZD94yDDNk0kgd6T4C
# 4gYU7Ih7X8ljGQIDAQABo4IC4zCCAt8wPgYJKwYBBAGCNxUHBDEwLwYnKwYBBAGC
# NxUIhZjgA4GMgFKHtYkmgcj0GoXn1DSBNoXD7XqFqeMuAgFlAgEDMBMGA1UdJQQM
# MAoGCCsGAQUFBwMDMAsGA1UdDwQEAwIHgDAbBgkrBgEEAYI3FQoEDjAMMAoGCCsG
# AQUFBwMDMB0GA1UdDgQWBBTcZSZwYk2fhTXwKNYRDnZWUrVw2TAfBgNVHSMEGDAW
# gBR/klkqLnMMMHSPYU/sdscw69+2IDCBzwYDVR0fBIHHMIHEMIHBoIG+oIG7hoG4
# bGRhcDovLy9DTj1zdWIzLUNBQm90aSxDTj1jYS1yb290LXByZCxDTj1DRFAsQ049
# UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJh
# dGlvbixEQz1ib3RpY2FyaW8sREM9bmV0P2NlcnRpZmljYXRlUmV2b2NhdGlvbkxp
# c3Q/YmFzZT9vYmplY3RDbGFzcz1jUkxEaXN0cmlidXRpb25Qb2ludDCBvwYIKwYB
# BQUHAQEEgbIwga8wgawGCCsGAQUFBzAChoGfbGRhcDovLy9DTj1zdWIzLUNBQm90
# aSxDTj1BSUEsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMs
# Q049Q29uZmlndXJhdGlvbixEQz1ib3RpY2FyaW8sREM9bmV0P2NBQ2VydGlmaWNh
# dGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MDkGA1Ud
# EQQyMDCgLgYKKwYBBAGCNxQCA6AgDB5hZV9zdG9rb0BncnVwb2JvdGljYXJpby5j
# b20uYnIwTwYJKwYBBAGCNxkCBEIwQKA+BgorBgEEAYI3GQIBoDAELlMtMS01LTIx
# LTE2MTA5NzE1Mi0xNTUzNDg1NTYzLTI3OTc3NTg3OC03MDE3MzMwDQYJKoZIhvcN
# AQELBQADggEBAKk/SdY+51VTO/QFDe1RbLBNsIwl5SlOlfEG2Vq8CylSDL2qJ5Cq
# SZ6CeQkUVsKNaOWCBB8oH1Rzj9ZMds3tiAEUGk788fvhRKoA82IjAoFEVMgon94/
# UO2kLYBaTKb2ef8/FydvCj8YlhC4AG4PwbS6LzRFG7La7WG1WfVC9lwU203McoKh
# OK+hks0aE7QR2zIx+b/srsHjRlf3GySE5TUCsznZPXGte4l7Lgf9iGzPiYDGuupb
# xn5TXmRgrg3CwUY0AVksTeumHfU6pX2g+pk+77hdDrl6W85Q/w2blkXuw+0LIukD
# y/HT6WEaWHELmRJRR/XV4kzV6IN169jn89MwggY/MIIFJ6ADAgECAhNmABEGjlcd
# TWUtvbHNAAQAEQaOMA0GCSqGSIb3DQEBCwUAMEExEzARBgoJkiaJk/IsZAEZFgNu
# ZXQxGTAXBgoJkiaJk/IsZAEZFglib3RpY2FyaW8xDzANBgNVBAMTBkNBQm90aTAe
# Fw0yMzA2MTMxOTUwMjFaFw0yODA2MTExOTUwMjFaMEYxEzARBgoJkiaJk/IsZAEZ
# FgNuZXQxGTAXBgoJkiaJk/IsZAEZFglib3RpY2FyaW8xFDASBgNVBAMTC3N1YjMt
# Q0FCb3RpMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArLYtILuNKudW
# wTbVgRdckWj4Alm1CX4/5rpX03yOo6uviInMceGDGaUsKLiqYdNV3Iccr2eaSYHw
# GA8Zr9c/QRoC3nFBsC3CulFpN7zxLOvHW6cMRINllHaksQp3KyIZrJAy1YKS4cjR
# s+qyUFVXCMLneehN6hLihvWziHP/o1IT4UWfGiyXa0f4mdYgFqni55WO5IivnY7d
# OvshC8b61yMc08/OvLg5HGm8iIp20iDPDLPvtvlraIFHPLLwabvq/C68Gpg9nSEc
# 4D+uAUcmjoS4TyMzQGPuMLe80LUpV7naJyEZbGQrANAX+zCvBloIB2ZyIvq0yWME
# Dxcs86uZaQIDAQABo4IDKTCCAyUwEAYJKwYBBAGCNxUBBAMCAQAwHQYDVR0OBBYE
# FH+SWSoucwwwdI9hT+x2xzDr37YgMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBB
# MAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFMs/gjo3
# 7CBoN/iuVn+pW89IUb4JMIIBfAYDVR0fBIIBczCCAW8wggFroIIBZ6CCAWOGgbRs
# ZGFwOi8vL0NOPUNBQm90aSgyKSxDTj1WTVBXSU44OTMsQ049Q0RQLENOPVB1Ymxp
# YyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24s
# REM9Ym90aWNhcmlvLERDPW5ldD9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jh
# c2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnSGOWZpbGU6Ly8vL1ZN
# UFdJTjg5My5ib3RpY2FyaW8ubmV0L0NlcnRFbnJvbGwvQ0FCb3RpKDIpLmNybIY0
# aHR0cDovL3Jvb3RjYS5ib3RpY2FyaW8ubmV0L0NlcnRFbnJvbGwvQ0FCb3RpKDIp
# LmNybIY5ZmlsZTovLy8vdm1wd2luODkzLmJvdGljYXJpby5uZXQvQ2VydEVucm9s
# bC9DQUJvdGkoMikuY3JsMIIBFgYIKwYBBQUHAQEEggEIMIIBBDCBpwYIKwYBBQUH
# MAKGgZpsZGFwOi8vL0NOPUNBQm90aSxDTj1BSUEsQ049UHVibGljJTIwS2V5JTIw
# U2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1ib3RpY2Fy
# aW8sREM9bmV0P2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZp
# Y2F0aW9uQXV0aG9yaXR5MFgGCCsGAQUFBzABhkxodHRwOi8vcm9vdGNhLmJvdGlj
# YXJpby5uZXQvQ2VydEVucm9sbC9WTVBXSU44OTMuYm90aWNhcmlvLm5ldF9DQUJv
# dGkoNCkuY3J0MA0GCSqGSIb3DQEBCwUAA4IBAQBfRbWFrJlb8geMQp0tTeDnTBxO
# znkozSHfC9gZjY9QiYFax4ZVM7AXNohOfYDTHCobJH3NOYtHbQbK+nO9DU14L/ba
# 1iFWvFhsZruy1MTDNZg5VPy4yW0X8ES7i+/u/TFNVd9pjkVyATTcdAAycRIf1URj
# VYbQOqrOdyerU1+KPJxeaWppwNrzk0JzZ2feKlc3bALMAkeAFtJZ3CpW2HTE0tCN
# QQAuAItQ6kRE2GWqrNsSiwUnkuR9lRtzBlLn0dkUTayrM0h6LV7gHq7mUfFP1Df9
# RJpjvHnzlFGUNehfrIoL0NDRnqKInlfSqUbBzvoayIz6AX/ARVJPgc1npedCMIIG
# rjCCBJagAwIBAgIQBzY3tyRUfNhHrP0oZipeWzANBgkqhkiG9w0BAQsFADBiMQsw
# CQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cu
# ZGlnaWNlcnQuY29tMSEwHwYDVQQDExhEaWdpQ2VydCBUcnVzdGVkIFJvb3QgRzQw
# HhcNMjIwMzIzMDAwMDAwWhcNMzcwMzIyMjM1OTU5WjBjMQswCQYDVQQGEwJVUzEX
# MBUGA1UEChMORGlnaUNlcnQsIEluYy4xOzA5BgNVBAMTMkRpZ2lDZXJ0IFRydXN0
# ZWQgRzQgUlNBNDA5NiBTSEEyNTYgVGltZVN0YW1waW5nIENBMIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAxoY1BkmzwT1ySVFVxyUDxPKRN6mXUaHW0oPR
# nkyibaCwzIP5WvYRoUQVQl+kiPNo+n3znIkLf50fng8zH1ATCyZzlm34V6gCff1D
# tITaEfFzsbPuK4CEiiIY3+vaPcQXf6sZKz5C3GeO6lE98NZW1OcoLevTsbV15x8G
# ZY2UKdPZ7Gnf2ZCHRgB720RBidx8ald68Dd5n12sy+iEZLRS8nZH92GDGd1ftFQL
# IWhuNyG7QKxfst5Kfc71ORJn7w6lY2zkpsUdzTYNXNXmG6jBZHRAp8ByxbpOH7G1
# WE15/tePc5OsLDnipUjW8LAxE6lXKZYnLvWHpo9OdhVVJnCYJn+gGkcgQ+NDY4B7
# dW4nJZCYOjgRs/b2nuY7W+yB3iIU2YIqx5K/oN7jPqJz+ucfWmyU8lKVEStYdEAo
# q3NDzt9KoRxrOMUp88qqlnNCaJ+2RrOdOqPVA+C/8KI8ykLcGEh/FDTP0kyr75s9
# /g64ZCr6dSgkQe1CvwWcZklSUPRR8zZJTYsg0ixXNXkrqPNFYLwjjVj33GHek/45
# wPmyMKVM1+mYSlg+0wOI/rOP015LdhJRk8mMDDtbiiKowSYI+RQQEgN9XyO7ZONj
# 4KbhPvbCdLI/Hgl27KtdRnXiYKNYCQEoAA6EVO7O6V3IXjASvUaetdN2udIOa5kM
# 0jO0zbECAwEAAaOCAV0wggFZMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYE
# FLoW2W1NhS9zKXaaL3WMaiCPnshvMB8GA1UdIwQYMBaAFOzX44LScV1kTN8uZz/n
# upiuHA9PMA4GA1UdDwEB/wQEAwIBhjATBgNVHSUEDDAKBggrBgEFBQcDCDB3Bggr
# BgEFBQcBAQRrMGkwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNv
# bTBBBggrBgEFBQcwAoY1aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lD
# ZXJ0VHJ1c3RlZFJvb3RHNC5jcnQwQwYDVR0fBDwwOjA4oDagNIYyaHR0cDovL2Ny
# bDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZFJvb3RHNC5jcmwwIAYDVR0g
# BBkwFzAIBgZngQwBBAIwCwYJYIZIAYb9bAcBMA0GCSqGSIb3DQEBCwUAA4ICAQB9
# WY7Ak7ZvmKlEIgF+ZtbYIULhsBguEE0TzzBTzr8Y+8dQXeJLKftwig2qKWn8acHP
# HQfpPmDI2AvlXFvXbYf6hCAlNDFnzbYSlm/EUExiHQwIgqgWvalWzxVzjQEiJc6V
# aT9Hd/tydBTX/6tPiix6q4XNQ1/tYLaqT5Fmniye4Iqs5f2MvGQmh2ySvZ180HAK
# fO+ovHVPulr3qRCyXen/KFSJ8NWKcXZl2szwcqMj+sAngkSumScbqyQeJsG33irr
# 9p6xeZmBo1aGqwpFyd/EjaDnmPv7pp1yr8THwcFqcdnGE4AJxLafzYeHJLtPo0m5
# d2aR8XKc6UsCUqc3fpNTrDsdCEkPlM05et3/JWOZJyw9P2un8WbDQc1PtkCbISFA
# 0LcTJM3cHXg65J6t5TRxktcma+Q4c6umAU+9Pzt4rUyt+8SVe+0KXzM5h0F4ejjp
# nOHdI/0dKNPH+ejxmF/7K9h+8kaddSweJywm228Vex4Ziza4k9Tm8heZWcpw8De/
# mADfIBZPJ/tgZxahZrrdVcA6KYawmKAr7ZVBtzrVFZgxtGIJDwq9gdkT/r+k0fNX
# 2bwE+oLeMt8EifAAzV3C+dAjfwAL5HYCJtnwZXZCpimHCUcr5n8apIUP/JiW9lVU
# Kx+A+sDyDivl1vupL0QVSucTDh3bNzgaoSv27dZ8/DCCBrwwggSkoAMCAQICEAuu
# Zrxaun+Vh8b56QTjMwQwDQYJKoZIhvcNAQELBQAwYzELMAkGA1UEBhMCVVMxFzAV
# BgNVBAoTDkRpZ2lDZXJ0LCBJbmMuMTswOQYDVQQDEzJEaWdpQ2VydCBUcnVzdGVk
# IEc0IFJTQTQwOTYgU0hBMjU2IFRpbWVTdGFtcGluZyBDQTAeFw0yNDA5MjYwMDAw
# MDBaFw0zNTExMjUyMzU5NTlaMEIxCzAJBgNVBAYTAlVTMREwDwYDVQQKEwhEaWdp
# Q2VydDEgMB4GA1UEAxMXRGlnaUNlcnQgVGltZXN0YW1wIDIwMjQwggIiMA0GCSqG
# SIb3DQEBAQUAA4ICDwAwggIKAoICAQC+anOf9pUhq5Ywultt5lmjtej9kR8YxIg7
# apnjpcH9CjAgQxK+CMR0Rne/i+utMeV5bUlYYSuuM4vQngvQepVHVzNLO9RDnEXv
# PghCaft0djvKKO+hDu6ObS7rJcXa/UKvNminKQPTv/1+kBPgHGlP28mgmoCw/xi6
# FG9+Un1h4eN6zh926SxMe6We2r1Z6VFZj75MU/HNmtsgtFjKfITLutLWUdAoWle+
# jYZ49+wxGE1/UXjWfISDmHuI5e/6+NfQrxGFSKx+rDdNMsePW6FLrphfYtk/FLih
# p/feun0eV+pIF496OVh4R1TvjQYpAztJpVIfdNsEvxHofBf1BWkadc+Up0Th8Eif
# kEEWdX4rA/FE1Q0rqViTbLVZIqi6viEk3RIySho1XyHLIAOJfXG5PEppc3XYeBH7
# xa6VTZ3rOHNeiYnY+V4j1XbJ+Z9dI8ZhqcaDHOoj5KGg4YuiYx3eYm33aebsyF6e
# D9MF5IDbPgjvwmnAalNEeJPvIeoGJXaeBQjIK13SlnzODdLtuThALhGtyconcVuP
# I8AaiCaiJnfdzUcb3dWnqUnjXkRFwLtsVAxFvGqsxUA2Jq/WTjbnNjIUzIs3ITVC
# 6VBKAOlb2u29Vwgfta8b2ypi6n2PzP0nVepsFk8nlcuWfyZLzBaZ0MucEdeBiXL+
# nUOGhCjl+QIDAQABo4IBizCCAYcwDgYDVR0PAQH/BAQDAgeAMAwGA1UdEwEB/wQC
# MAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwIAYDVR0gBBkwFzAIBgZngQwBBAIw
# CwYJYIZIAYb9bAcBMB8GA1UdIwQYMBaAFLoW2W1NhS9zKXaaL3WMaiCPnshvMB0G
# A1UdDgQWBBSfVywDdw4oFZBmpWNe7k+SH3agWzBaBgNVHR8EUzBRME+gTaBLhklo
# dHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkRzRSU0E0MDk2
# U0hBMjU2VGltZVN0YW1waW5nQ0EuY3JsMIGQBggrBgEFBQcBAQSBgzCBgDAkBggr
# BgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMFgGCCsGAQUFBzAChkxo
# dHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkRzRSU0E0
# MDk2U0hBMjU2VGltZVN0YW1waW5nQ0EuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQA9
# rR4fdplb4ziEEkfZQ5H2EdubTggd0ShPz9Pce4FLJl6reNKLkZd5Y/vEIqFWKt4o
# KcKz7wZmXa5VgW9B76k9NJxUl4JlKwyjUkKhk3aYx7D8vi2mpU1tKlY71AYXB8wT
# LrQeh83pXnWwwsxc1Mt+FWqz57yFq6laICtKjPICYYf/qgxACHTvypGHrC8k1TqC
# eHk6u4I/VBQC9VK7iSpU5wlWjNlHlFFv/M93748YTeoXU/fFa9hWJQkuzG2+B7+b
# MDvmgF8VlJt1qQcl7YFUMYgZU1WM6nyw23vT6QSgwX5Pq2m0xQ2V6FJHu8z4LXe/
# 371k5QrN9FQBhLLISZi2yemW0P8ZZfx4zvSWzVXpAb9k4Hpvpi6bUe8iK6WonUSV
# 6yPlMwerwJZP/Gtbu3CKldMnn+LmmRTkTXpFIEB06nXZrDwhCGED+8RsWQSIXZpu
# G4WLFQOhtloDRWGoCwwc6ZpPddOFkM2LlTbMcqFSzm4cd0boGhBq7vkqI1uHRz6F
# q1IX7TaRQuR+0BGOzISkcqwXu7nMpFu3mgrlgbAW+BzikRVQ3K2YHcGkiKjA4gi4
# OA/kz1YCsdhIBHXqBzR0/Zd2QwQ/l4Gxftt/8wY3grcc/nS//TVkej9nmUYu83BD
# tccHHXKibMs/yXHhDXNkoPIdynhVAku7aRZOwqw6pDGCBTMwggUvAgEBMF0wRjET
# MBEGCgmSJomT8ixkARkWA25ldDEZMBcGCgmSJomT8ixkARkWCWJvdGljYXJpbzEU
# MBIGA1UEAxMLc3ViMy1DQUJvdGkCE0oABRHGgqKHvXzQ0PsAAAAFEcYwDQYJYIZI
# AWUDBAIBBQCggYQwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0B
# CQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAv
# BgkqhkiG9w0BCQQxIgQgP54XI8OwWCOa/Um92mu3BCffuc3bMg4W5EAaXfomn4ow
# DQYJKoZIhvcNAQEBBQAEggEAhNGSFIjAncMrWk+C7LLbZ6bJl5G45RvUWEv2lN9g
# oRShIDgRH+akviGhH35TbitgKia4y14alzC0ozO1sdJ/fV5YfBs/KmLFTOvH7MWH
# TifqrO+WlRb95ytoU3DThUwfqA6+SGxnY6FTb17d6/nzlINyhlX+3Kx9xy0ZenYg
# 24nidNb685zOxRlrDVPsJ6qcCWlUCIl06P30MKTtC6DV+ntHWx9Nv0GfMsypyR3o
# DPgIpqYdSxVUwlci0qEr+Qh1myLoQQps5kFsY3lkWw//TnAXirv3M5sROPzQKQ1G
# GXf/PoH+jnRJwyp7RZkNMiwjz0SRe6KnnbGQGHBrqIqaZaGCAyAwggMcBgkqhkiG
# 9w0BCQYxggMNMIIDCQIBATB3MGMxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdp
# Q2VydCwgSW5jLjE7MDkGA1UEAxMyRGlnaUNlcnQgVHJ1c3RlZCBHNCBSU0E0MDk2
# IFNIQTI1NiBUaW1lU3RhbXBpbmcgQ0ECEAuuZrxaun+Vh8b56QTjMwQwDQYJYIZI
# AWUDBAIBBQCgaTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJ
# BTEPFw0yNTA1MjgxNjMzMTJaMC8GCSqGSIb3DQEJBDEiBCBDgxwIEh+tlUdGT/1m
# sTNgHTk44SHwaDDhcNAtjzD22jANBgkqhkiG9w0BAQEFAASCAgA678iolBcVHCAX
# nCpFfKvzeUIBT10TsU6i413A2LFCGgQLzS57DtIkIzazFUcmR8vso7YTcB9F1p2k
# Hv0EuTjHALYQHTp8oc/PUYnMXOhfUfmq5BCeQHl5kb/S/ts7ZhLlyZp0l3uvXCYI
# trCu9bTuakuab4C497/nv2J9MUAZBkSQ/OV+0uTamIFqUo45McVvjafmq82+ISAW
# CNKInVc5vjbfZln0jMGAkwjLXYVWylfY1DtXsWIQPGE9NhxaYOjDij3JmQG/EUbN
# DNIx7hwSjvsOryEO9inV4h/xRVwQo5v33UV1MkOcJq9zlCbsMFgpQ/eKNbwpDJp5
# 0J5WNsmVCR0mIGTKHGbqvj6IIyYmkGI5idUgwEppovypP9NPWAqxo7u+TDiGMDxw
# FOKz+2BNYTuG5Ovn8Ns01R7JoeOiDi4kkcylZGKS8bncaJHixtOBIA+paEt6+GH2
# 5kx9WiXKHMYOpLwhoJ+Hj2Et6xVmMP5FwEcK+3rg2ctinTAuMa+9te95Du6KJQUM
# SqXs2/yspGEH/pTbIVi7aSIVkdS3FpQHVlLhA+6HsC0U/1xbOulA2NfY9Mdi4hNA
# 0GGIRyKnWYnDWV8S0kO6EC+LGU9tsobd6VxQiJ3GWdsrD3/KX/IDZfMXOBEf/8Vy
# 2bmAvfh3OmYJrjjbz/jjPIH3oc6Ydg==
# SIG # End signature block
